#!/usr/bin/expect

spawn ssh linaro@192.168.0.22
expect "password"
send "linaro\r"
expect "linaro"
send "sudo su\r"
expect "password"
send "linaro\r"
expect "root"
send "./px4 mainconfig.app\r"
interact
