#!/usr/bin/expect

spawn ssh linaro@192.168.1.22
expect "password"
send "linaro\r"
expect "linaro"
send "sudo su\r"
expect "linaro"
expect "root"
interact
send "roslaunch mavros px4.launch fcu_url:="udp://:14550@192.168.1.22:14556\r"
interact

